# Define build arguments
ARG IMAGE_BASE=alpine
ARG IMAGE_VERSION=3.20.0

# Stage 2: Run
FROM ${IMAGE_BASE}:${IMAGE_VERSION}

# Install Python runtime
RUN apk add --no-cache python3

# Set the working directory
WORKDIR /app

# Copy the application source code and virtual environment from the build stage
COPY --from=build /app /app

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/venv/bin:$PATH"

# Run the application
CMD ["python3", "app/main.py"]
