# Dockerfile.test-alpine

ARG IMAGE_BASE=alpine-builder
ARG IMAGE_VERSION=latest

FROM ${IMAGE_BASE}:${IMAGE_VERSION} AS test-alpine

ARG APP_USER=codespace

# Install Python runtime
RUN apk add --no-cache python3

# Create a user to run the app
RUN addgroup -S appgroup && adduser -S ${APP_USER} -G appgroup

# Set the working directory
WORKDIR /app

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/venv/bin:$PATH"

# Copy the application source code and virtual environment from the build stage
COPY --from=alpine-builder /app /app

# Set the user to use when running this image
USER ${APP_USER}

# Run the tests
CMD ["pytest", "--disable-warnings"]
