ARG IMAGE_BASE=ubuntu
ARG IMAGE_VERSION=20.04
ARG BUILDER_IMAGE
ARG BUILDER_VERSION

FROM ${BUILDER_IMAGE}:${BUILDER_VERSION} as base
FROM ${IMAGE_BASE}:${IMAGE_VERSION} as final

# Install Python runtime
RUN apt-get update && \
    apt-get install -y python3 && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the application source code and virtual environment from the build stage
COPY --from=base /app /app

# Set the user to use when running this image
ARG APP_USER=codespace
RUN useradd -m ${APP_USER}
USER ${APP_USER}

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/venv/bin:$PATH"

# Run tests
CMD ["pytest", "--disable-warnings"]
