import os

# Define the directory structure and descriptions
structure = {
    '.': {
        'description': 'Root directory of the Docker project.',
        'subdirs': {
            'src': {
                'description': 'Source code of the application.',
                'subdirs': {
                    'app': {
                        'description': 'Main application code.',
                        'subdirs': {}
                    },
                    'config': {
                        'description': 'Configuration files for the application.',
                        'subdirs': {}
                    },
                    'static': {
                        'description': 'Static files like CSS, JavaScript, and images.',
                        'subdirs': {}
                    },
                    'templates': {
                        'description': 'HTML templates for the application.',
                        'subdirs': {}
                    },
                    'tests': {
                        'description': 'Test files for the application.',
                        'subdirs': {}
                    }
                }
            },
            'scripts': {
                'description': 'Scripts for building, starting, and managing the application.',
                'subdirs': {}
            },
            'logs': {
                'description': 'Log files generated by the application.',
                'subdirs': {}
            },
            'data': {
                'description': 'Data files and directories.',
                'subdirs': {}
            },
            'docs': {
                'description': 'Documentation for the project.',
                'subdirs': {}
            }
        }
    }
}

# Function to create directories and write descriptions
def create_structure(base_path, structure):
    for dirname, props in structure.items():
        dir_path = os.path.join(base_path, dirname)
        os.makedirs(dir_path, exist_ok=True)
        
        # Create description file
        description_file = os.path.join(dir_path, 'description.txt')
        with open(description_file, 'w') as f:
            f.write(props['description'])
        
        # Recurse into subdirectories
        create_structure(dir_path, props['subdirs'])

# Create the directory structure
base_path = '.'  # Current directory
create_structure(base_path, structure)
